apiVersion: v1
kind: Namespace
metadata:
  name: op-otel

---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: op-otel
  namespace: op-otel

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: otel-operator
  namespace: op-otel
spec:
  channel: alpha
  name: opentelemetry-operator
  source: operatorhubio-catalog
  sourceNamespace: olm

---

apiVersion: v1
kind: Namespace
metadata:
  name: poc-rust

---

apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-rust
  namespace: poc-rust
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    exporters:
      debug: {}
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          exporters: [debug]
        logs:
          receivers: [otlp]
          exporters: [debug]

