apiVersion: v1
kind: Namespace
metadata:
  name: op-otel

---

# $ operator-sdk olm install
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: op-otel
  namespace: op-otel

---

# https://operatorhub.io/install/opentelemetry-operator.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: otel-operator
  namespace: op-otel
spec:
  channel: alpha
  name: opentelemetry-operator
  source: operatorhubio-catalog
  sourceNamespace: olm

---

# https://operatorhub.io/install/tempo-operator.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tempo-operator
  namespace: op-otel
spec:
  channel: alpha
  name: tempo-operator
  source: operatorhubio-catalog
  sourceNamespace: olm

---

# https://operatorhub.io/install/loki-operator.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: loki-operator
  namespace: op-otel
spec:
  channel: alpha
  name: loki-operator
  source: operatorhubio-catalog
  sourceNamespace: olm

---

# https://operatorhub.io/install/prometheus.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus-operator
  namespace: op-otel
spec:
  channel: beta
  name: prometheus
  source: operatorhubio-catalog
  sourceNamespace: olm

---

# https://operatorhub.io/install/grafana-operator.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: op-otel
spec:
  channel: v5
  name: grafana-operator
  source: operatorhubio-catalog
  sourceNamespace: olm

---

apiVersion: v1
kind: Namespace
metadata:
  name: poc-rust

---

apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-rust
  namespace: poc-rust
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    exporters:
      debug: {}
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          exporters: [debug]
        logs:
          receivers: [otlp]
          exporters: [debug]

