[package]
name = "statistic"
version = "0.1.0"
edition = "2024"

[dependencies]
envfile = "0.2.1"
tree-sitter = "0.25.8"
tree-sitter-java = "0.23.5"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
tracing-subscriber = "0.3.19"
log = "0.4.27"
